# Hacer el merge de los datos del presu inicial

In [3]:
# Importación  y areglo del Presupuesto inicial

##################################################################################################
##################################################################################################
#                         Establecimiento de la  configuración general                           #
##################################################################################################
##################################################################################################

################
#  Librerías   #
################

import numpy as np
import pandas as pd


pd.set_option('display.float_format', lambda x: '%.1f' % x)

################
#  Directorio  #
################ 

import os
cwd = os.getcwd()
cwd
# Print the current working directory
print("Current working directory: {0}".format(cwd))


path = 'C:\\Users\\oscar\\Desktop\\GitHub\\Python\\Projetcs\\P3\\Data-Manipulation-with-Python\\Income\\data'
# Change the current working directory
os.chdir(path)
# Let's check the new directory 
print("Current working directory: {0}".format(os.getcwd()))


#####################################################
#####################################################
#         Parámetros: datos + dashboard             #
#####################################################
#####################################################

#############
#  Millones #
#############

Millones = 1000000
# print(Millones)

################################
#  Delimitación años análisis  #
################################

Anos_analisis = 2007
# print(Anos_analisis)

####################
#  Años referencia #
####################

import datetime
today = datetime.date.today()
Año = today.year

Current working directory: c:\Users\oscar\Desktop\GitHub\Python\Projetcs\P3\Data-Manipulation-with-Python\Income
Current working directory: C:\Users\oscar\Desktop\GitHub\Python\Projetcs\P3\Data-Manipulation-with-Python\Income\data

In [8]:
#####
# 1 #  
##################################################################################################
##################################################################################################
##################################################################################################
#                              Importación de los ingresos                                       #
##################################################################################################
##################################################################################################
##################################################################################################

#############################
#   Ingresos  2007 - 2020   #
#############################

ingresos_2007_2021 = pd.read_excel('SIGAF_2007_2021.xlsx') 
# print(ingresos_2007_2021.shape)
# print(ingresos_2007_2021.columns)


###############################
#   Ingresos  SIGAF  actual   #
###############################

# Este si se debe llamar siempre "SIGAF_Ingresos_actual."

SIGAF_Ingresos_actual = pd.read_excel('SIGAF_Ingresos_actual.xlsx') 

SIGAF_Ingresos_actual['PosPre'] = SIGAF_Ingresos_actual['PosPre'].replace(['I'],'I0000000000000')
# print(SIGAF_Ingresos_actual.shape)
# print(SIGAF_Ingresos_actual.columns)

###############################################
#   Presupuesto inicial   #
###############################################

PPI = pd.read_excel('PPI.xlsx', converters={
                                            'Año':str,
                                            'Clase':str,
                                            'Subclase':str,
                                            'Grupo':str,
                                            'Subgrupo':str,
                                            'Partida':str,
                                            'Subpartida':str,
                                            'Renglón':str,
                                            'Subrenglón':str,
                                            'Fuente finaciamiento':str,
                                            'Descripción':str,
                                            'Presupuesto inicial': float
                                            }
                    ) 
# print(PPI.shape)
# print(PPI.columns)

In [10]:
PPI['Pospreanual'] = PPI[['Año','Clase','Subclase','Grupo','Subgrupo','Partida','Subpartida','Renglón','Subrenglón','Fuente finaciamiento']].agg(''.join, axis=1)
PPI_a = PPI.loc [:, ['Pospreanual','Presupuesto inicial']]
PPI_a

            Pospreanual  Presupuesto inicial
0     20140000000000000      6651446000000.0
1     20141000000000000      3810013000000.0
2     20141100000000000      3542803000000.0
3     20141110000000000      1084600000000.0
4     20141111000000000       367400000000.0
...                 ...                  ...
2141  20213311010000911           74999683.0
2142  20213320000000000          828274863.1
2143  20213321010000923          374609939.3
2144  20213321010000940           96000000.0
2145  20213321010000951          357664923.8

[2146 rows x 2 columns]

In [17]:
##################################################################################################
##################################################################################################
##################################################################################################
#                                  Ingresos  Anuales                                             #
##################################################################################################
##################################################################################################
##################################################################################################

#############################
#   Ingresos  20167-2020     #
#############################

ingresos_2007_2021_a = ingresos_2007_2021 
# ingresos_2007_2021_a.info()

# Año = today.year

SIGAF_Ingresos_actual_a = SIGAF_Ingresos_actual
SIGAF_Ingresos_actual_a['Año'] = Año



# SIGAF_Ingresos_actual_a.info()

# ingresos_2007_2021_a.columns = SIGAF_Ingresos_actual_a.columns


# Ingresos_a = pd.merge(ingresos_2007_2021_a, SIGAF_Ingresos_actual_a, on='name')

Ingresos_a = pd.concat([ingresos_2007_2021_a, SIGAF_Ingresos_actual_a], axis=0, ignore_index=True )

convert_dict_2 = {'Año': str
                }

Ingresos_a = Ingresos_a.astype(convert_dict_2)

print(Ingresos_a.shape)
Ingresos_a
# Ingresos_a.tail(15)

(4257, 21)

,Año,Nivel,PosPre,Desc.Pos.presupuestaria,Presupuesto Actual,Devengado Enero,Devengado Febrero,Devengado Marzo,Devengado Abril,Devengado Mayo,...,Devengado Julio,Devengado Agosto,Devengado Setiembre,Devengado Octubre,Devengado Noviembre,Devengado Diciembre,Devengado Acumulado,Dif Pto Estimado – Ac Real,Ingreso acumulado real,Pendiente-Excedente
0,2007,0,I0000000000000,INGRESOS TOTAL,2953611470129.7,173183646369.0,166188486454.4,324791941831.9,180612510798.4,165896012467.6,...,228554614950.7,213815242604.5,256094162326.8,256171332340.8,252985957067.5,347411770866.5,2730722819268.9,222888650860.8,92.5,7.5
1,2007,1,I1000000000000,INGRESOS CORRIENTESI,1869707499062.1,172029276262.4,134458786659.7,189188472641.8,158535729835.5,152767529299.6,...,179013953883.8,149486783809.3,154571908309.5,192718654536.5,167797464512.7,291286037320.8,2104451052531.2,-234743553469.1,112.6,-12.6
2,2007,2,I1100000000000,INGRESOS TRIBUTARIOS,1802746862763.0,166413106592.5,130637062419.2,185830187991.3,154728905374.4,141432413704.6,...,173097204368.0,142732287856.0,149542574754.2,187977973128.6,162792407735.7,283988423604.6,2028941824871.5,-226194962108.5,112.5,-12.6
3,2007,3,I1110000000000,IMP. S/ ING Y UTIL,437000000000.0,33714166084.3,21571801082.1,72392056721.3,42521382501.4,18361843790.2,...,49239135914.9,16501978460.9,29659932851.4,62144120488.2,23627620876.7,114933728244.9,531551766603.9,-94551766603.9,121.6,-21.6
4,2007,4,I1111000000000,IMP. ING Y UTI PER F,111000000000.0,15517617248.3,973447360.9,9665974155.6,4159684518.1,9358841486.0,...,1051165033.1,17863259569.8,8098490728.5,9112845411.3,1086614742.3,40819856399.1,123194061450.7,-12194061450.7,111.0,-11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4252,2022,4,I3321010000952,Superávit Específico Sistema Nacional de Áreas...,6211398090.3,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,6211398090.3,0.0,NaN,NaN,6211398090.3,0.0,100.0,0.0
4253,2022,4,I3321010000953,Superávit Específico Patronato de Construccion...,4217954601.2,0.0,0.0,0.0,4217954601.2,0.0,...,0.0,0.0,0.0,0.0,NaN,NaN,4217954601.2,0.0,100.0,0.0
4254,2022,4,I3321010000958,Superávit Específico Comisión Nacional de Vacu...,500290578.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,500290578.0,0.0,NaN,NaN,500290578.0,0.0,100.0,0.0
4255,2022,4,I3321010000959,Superávit Específico Fondo de Desarrollo Socia...,7490422463.7,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,7490422463.7,0.0,NaN,NaN,7490422463.7,0.0,100.0,0.0
4256,2022,4,I3321010000960,Superávit Específico Instituto Costarricense d...,99430707.3,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,99430707.3,0.0,NaN,NaN,99430707.3,0.0,100.0,0.0

In [18]:
# Ingresos_a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4257 entries, 0 to 4256
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Año                         4257 non-null   object
 1   Nivel                       4257 non-null   int64
 2   PosPre                      4257 non-null   object
 3   Desc.Pos.presupuestaria     4257 non-null   object
 4   Presupuesto Actual          4257 non-null   float64
 5   Devengado Enero             4257 non-null   float64
 6   Devengado Febrero           4257 non-null   float64
 7   Devengado Marzo             4257 non-null   float64
 8   Devengado Abril             4254 non-null   float64
 9   Devengado Mayo              4257 non-null   float64
 10  Devengado Junio             4257 non-null   float64
 11  Devengado Julio             4257 non-null   float64
 12  Devengado Agosto            4257 non-null   float64
 13  Devengado Setiembre         4257 non-null   float64
 14  Devengado Octubre           4257 non-null   float64
 15  Devengado Noviembre         3795 non-null   float64
 16  Devengado Diciembre         3795 non-null   float64
 17  Devengado Acumulado         4257 non-null   float64
 18  Dif Pto Estimado – Ac Real  4257 non-null   float64
 19  Ingreso acumulado real      4257 non-null   float64
 20  Pendiente-Excedente         4257 non-null   float64
dtypes: float64(17), int64(1), object(3)
memory usage: 698.5+ KB

In [24]:
###########################################################
#       Transformación de datos                           #
###########################################################

Ingresos_a['Pospre']         = Ingresos_a['PosPre'].str.slice(1,14)
Ingresos_a['Pospreanual']    = Ingresos_a[['Año','Pospre']].agg(''.join, axis=1)
Ingresos_a = Ingresos_a.reindex(columns=['Año', 'Nivel', 'n_Nivel' ,'PosPre','Pospre','Pospreanual', 'cod_sector','Presupuesto actual', 'mes.cod','mes','cod_clase','clase','cod_subclase','subclase','cod_grupo','grupo','cod_subgrupo','subgrupo',
         'cod_partida','cod_subpartida','cod_renglon','cod_subrenglon', 'cod_fuentefinanciacion','cod_fuentefinanciacion_3','Descripción','Ingresos'])
# Ingresos_a.info()
Ingresos_a.shape

(4257, 26)

In [26]:

Ingresos_a_merge = pd.merge(Ingresos_a, PPI_a, how='left', on='Pospreanual')
Ingresos_a_merge.shape

(4257, 27)

In [27]:
Ingresos_a_merge

,Año,Nivel,n_Nivel,PosPre,Pospre,Pospreanual,cod_sector,Presupuesto actual,mes.cod,mes,...,subgrupo,cod_partida,cod_subpartida,cod_renglon,cod_subrenglon,cod_fuentefinanciacion,cod_fuentefinanciacion_3,Descripción,Ingresos,Presupuesto inicial
0,2007,0,NaN,I0000000000000,0000000000000,20070000000000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2007,1,NaN,I1000000000000,1000000000000,20071000000000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2007,2,NaN,I1100000000000,1100000000000,20071100000000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2007,3,NaN,I1110000000000,1110000000000,20071110000000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2007,4,NaN,I1111000000000,1111000000000,20071111000000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4252,2022,4,NaN,I3321010000952,3321010000952,20223321010000952,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4253,2022,4,NaN,I3321010000953,3321010000953,20223321010000953,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4254,2022,4,NaN,I3321010000958,3321010000958,20223321010000958,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4255,2022,4,NaN,I3321010000959,3321010000959,20223321010000959,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4256,2022,4,NaN,I3321010000960,3321010000960,20223321010000960,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN